/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./theme/components/demo.vue')['default']
    ImageViewer: typeof import('./theme/components/imageViewer.vue')['default']
    SubPage: typeof import('./theme/components/subPage.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
  }
}
