/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./theme/components/demo.vue')['default']
    ImageViewer: typeof import('./theme/components/imageViewer.vue')['default']
    ListStyleType: typeof import('./examples/frontend/css/listStyleType.vue')['default']
    Mylink: typeof import('./theme/components/mylink.vue')['default']
    OutlineAutoScroll: typeof import('./theme/components/outlineAutoScroll.vue')['default']
    Run: typeof import('./theme/components/run.vue')['default']
    SubPage: typeof import('./theme/components/subPage.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TList: typeof import('tdesign-vue-next')['List']
    TListItem: typeof import('tdesign-vue-next')['ListItem']
    TListItemMeta: typeof import('tdesign-vue-next')['ListItemMeta']
    TSpace: typeof import('tdesign-vue-next')['Space']
    Version: typeof import('./theme/components/version.vue')['default']
    VscodeExtensionList: typeof import('./examples/other/vscodeExtensionList.vue')['default']
  }
}
